#! /usr/bin/env bash

inp=`echo -e "" | dmenu -p "English to arabic" -b -sb "#00aa00" -sf "#000000" -nb "#000000" -nf "#00aa00"`

if [[ $inp != "" ]] 
then
res=`python $HOME/.scripts/eta.py $inp`
echo res
echo $res | xclip -selection c
notify-send "$res was coppied"
fi

