#!/usr/bin/env bash
xdotool search --sync --syncsleep 10 --limit 1 --class Rofi keyup --delay 0 Tab key --delay 0 Tab keyup --delay 0 Super_L keydown --delay 0 Super_L&

rofi \
      -show window  \
      -selected-row 1 \
      -kb-accept-entry "!Alt-Tab,!Alt+Alt_L"\
      -kb-row-down "Alt+Tab" \
