#! /bin/sh

/home/$USER/.config/bspwm/bsp_settings

# launch applications
feh --bg-center  ~/Wallpapers/310923.jpg


$HOME/.config/polybar/launch.sh


alttab -w 1 -d 2 -bg "#252834" -fg "#ffffff" -frame "#AA33AA" -t 110x80 -i 110x32 &

wmname LG3D

artha &
emote &
