#! /usr/bin/env bash

s=`echo -e "" | dmenu -i -p "Wikipedia search" -b -sb "#ffffff" -sf "#000000" -nb "#000000" -nf "#ffffff"`

if [[ $s != "" ]] 
then
	$BROWSER https://en.wikipedia.org/w/index.php?search=$s
fi
