#! /usr/bin/env bash

s=`simple-mtpfs -l | dmenu -i -p "Select your phone" -b -sb "#00aa00" -sf "#000000" -nb "#000000" -nf "#00aa00"`

id=`~/.scripts/get_cell_id $s`

if [[ $s != "" ]] 
then
mkdir -p ~/cell-$id
simple-mtpfs --device $id ~/cell-$id
fi
