#! /usr/bin/env bash

p="/run/media/$USER/MyProjects"
echo $p
cd $p

s=`ls -d */| dmenu -i -l 10 -p "My Projects" -b -sb "#aaaa54" -sf "#0f3314" -nb "#0f3314" -nf "#aaaa54"`

if [[ $s != "" ]] 
then
    cd $p/$s
    $TERMINAL 
fi
