#! /usr/bin/env bash

p="/run/media/asiam/MyProjects"
echo $p
cd $p

s=`ls -d */| dmenu -l 10 -p "My Projects" -b -sb "#aaaa54" -sf "#0f3314" -nb "#0f3314" -nf "#aaaa54"`

if [[ $s != "" ]] 
then
    cd $p/$s
    $TERMINAL -e sh -c $FILEEXP 
fi
