#! /usr/bin/env bash

s=`echo -e "" | dmenu -p "Arch Wiki search" -b -sb "#1793D1" -sf "#000000" -nb "#000000" -nf "#1793D1"`

if [[ $s != "" ]] 
then
	$BROWSER https://wiki.archlinux.org/index.php?search=$s
fi
