#!/usr/bin/env bash
choise=`echo -e "word\npowerpoint\nexcel" | dmenu -sb "#a062aa" -nb "#000011" -b`
if [[ $choise == "word" ]] 
then
    wine ~/win32/drive_c/Program\ Files/Microsoft\ Office/Office12/WINWORD.EXE
elif [[ $choise == "powerpoint" ]]
then
    wine ~/win32/drive_c/Program\ Files/Microsoft\ Office/Office12/POWERPNT.EXE
elif [[ $choise == "excel" ]]
then
    wine ~/win32/drive_c/Program\ Files/Microsoft\ Office/Office12/EXCEL.EXE
else 
    echo "dmenu-msoffice: no correct choise selected"
fi
