#! /usr/bin/env bash

cd /run/media/asiam/MyFiles/CSE_selfstudy

s=`ls -d */| dmenu -l 10 -p "Self Studing" -b -sb "#77B454" -sf "#0A0E14" -nb "#0A0E14" -nf "#77B454"`

if [[ $s != "" ]] 
then
    cd ./"$s"
    $TERMINAL -e sh -c $FILEEXP
fi
