#!/usr/bin/env bash
choise=`echo -e "word\npowerpoint\nexcel\nphotoshop" | dmenu -i -sb "#a062aa" -nb "#000011" -b`
if [[ $choise == "word" ]] 
then
    wine "/home/a/.wine/drive_c/Program Files (x86)/Microsoft Office/Office12/WINWORD.EXE"
elif [[ $choise == "powerpoint" ]]
then
    wine "/home/a/.wine/drive_c/Program Files (x86)/Microsoft Office/Office12/POWERPNT.EXE"
elif [[ $choise == "excel" ]]
then
    wine "/home/a/.wine/drive_c/Program Files (x86)/Microsoft Office/Office12/EXCEL.EXE"
elif [[ $choise == "photoshop" ]]
then
    cd "/run/media/$USER/MyFiles/Software/WindowsSoftwares/Adobe Photoshop CS5 ME Portable/Adobe Photoshop CS5 ME Portable"
    wine Adobe\ Photoshop\ CS5\ ME\ Portable.exe
else 
    echo "dmenu -i-msoffice: no correct choise selected"
fi
