#!/usr/bin/env bash
inp=`echo "" | rofi -dmenu`
if [[ $inp != "" ]]
then
    $BROWSER "https://www.pdfdrive.com/search?q=$inp"
    $BROWSER "http://libgen.rs/search.php?req=$inp"
    $BROWSER "https://b-ok.africa/s/$inp"
fi
